### ISSUE TITLE
corrigir evidencia de licença pk_005

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-CO#8]
Alguns problemas foram detectados em [_pk005/make_conf](https://github.com/digital-guard/preserv-CO/blob/main/data/_pk005/make_conf.yaml), corrigir...
```
license_evidences:
    definition: [Cláusula de Licencia Abierta,OpenDefinition , http://visor.codigopostal.gov.co/472/visor/Clausula_Licencia_Abierta.pdf]
    file: 7502b5c3cd701ac21c126c8d6e133bcf2d082e7d08e37acf7d1977e636e0488c.zip
    uri_evidency: http://web.archive.org/web/20211012105347/https://www.openstreetmap.org/copyright
    by_explicit: MINTIC - Servicios Postales Nacionales 4-72 (Unidad Código Postal Colombia)
```

1. A licença de código postal da Colômbia não tem nada haver com OpenStreetMap ou `openstreetmap.org/copyright`, não faz sentido usar isso como `uri_evidency` 
2. A licença infelizmente não tem origem em padrões como CC, vai precisar de uma interpretação. Ela pelo menos cita [Open Definition](https://opendefinition.org/od/2.1/es/), de modo que temos uma referência interpretativa conhecida. A família da licença deve ser deduzida através dela.
3.  Não existe "família Open Definition" em [licenses/data/families.csv](https://github.com/digital-guard/licenses/blob/master/data/families.csv), e a interpretação livre sugere que a família seja CC-BY.

Na prática, quando não é uma licença explicita padrão é preciso recorrer ao "julgamento da licença" 

... Por hora, até que não se julgue a licença,  é razoável apenas corrigir para:
```
license_evidences:
    definition: [Licencia-codigopostal.gov.co, CC-BY? , http://visor.codigopostal.gov.co/472/visor/Clausula_Licencia_Abierta.pdf]
    file: 7502b5c3cd701ac21c126c8d6e133bcf2d082e7d08e37acf7d1977e636e0488c.zip
    uri_evidency: https://web.archive.org/web/20210907144722/http://visor.codigopostal.gov.co/472/visor/Clausula_Licencia_Abierta.pdf
    by_explicit: MINTIC - Servicios Postales Nacionales 4-72 (Unidad Código Postal Colombia)
```

Por ser uma licença de dados nova, será preciso solicitar uma nova entrada em http://git.digital-guard.org/licenses/blob/master/data/licenses.csv

------

Por favor solicitar na interface de discussão,  https://github.com/digital-guard/licenses/discussions/1  a avaliação [desta licença](http://visor.codigopostal.gov.co/472/visor/Clausula_Licencia_Abierta.pdf).
